# Generated by Django 4.2.5 on 2023-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_avaliacao',
            name='nome_tipo_avaliacao',
            field=models.CharField(max_length=20),
        ),
    ]
