# Generated by Django 4.2.5 on 2023-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nome_tipo_avaliacao_tipo_avaliacao_tipo_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestres',
            name='quantidade_periodo',
            field=models.CharField(max_length=2),
        ),
    ]
